---
- name: Install Git, Node.js, and Docker on RHEL 9 EC2 instance
  hosts: ec2_instances
  become: true
  tasks:

    # Install Git
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install node required packages
      ansible.builtin.yum:
        name:
          - gcc-c++
          - make
        state: present
        
    # Add the Node.js 16.x repository
    - name: Add NodeSource repository for node.js 16
      ansible.builtin.yum_repository:
        name: nodesource
        description: Node.js Packages for RHEL $basearch
        baseurl: https://rpm.nodesource.com/pub_16.x/el/9/$basearch
        gpgcheck: yes
        gpgkey: https://rpm.nodesource.com/pub_16.x/el/NODESOURCE-GPG-SIGNING-KEY-EL
        enabled: yes
        state: present

    # Install Node.js 16
    - name: Install Node.js 16
      ansible.builtin.yum:
        name: nodejs
        state: present

    # Verify Node.js and npm versions
    - name: Verify Node.js version
      ansible.builtin.shell: |
        node -v
        npm -v
      register: node_version
      changed_when: false

    - name: Display the nodejs version
      ansible.builtin.debug:
        msg: "Node.js version: {{ node_version.stdout_lines }}"

    - name: Show installed npm version
      debug:
        msg: "npm version: {{ npm_version.stdout }}"

    # Install Docker
    - name: Install required packages for Docker
      yum:
        name: 
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/rhel/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/rhel/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/rhel/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started
